/**
 * Phoenix Police Department radio codes, word for word from the
 * department's published list, updated 3/17/26:
 * phoenix.gov, "Radio Codes Numerical Alphabetical". A code may carry a
 * modifier: X for an attempt, S for a supplement, BC for a broadcast.
 *
 * The category beside each is the bench's own grouping, for sorting calls.
 */

import type { CodeCategory } from './categories'

export const PHOENIX_PD: Record<string, { meaning: string; category: CodeCategory }> = {
  '2': { meaning: 'urgent - no red lights / siren', category: 'status' },
  '3': { meaning: 'emergency - red lights &siren', category: 'status' },
  '4': { meaning: 'no further assistance needed', category: 'status' },
  '5': { meaning: 'stake out - other units stay away', category: 'status' },
  '6': { meaning: 'out for investigation (citation, 10-29, etc.)', category: 'status' },
  '7': { meaning: 'out of service to eat', category: 'status' },
  '101': { meaning: 'woman in the car', category: 'status' },
  '102': { meaning: 'woman out of the car', category: 'status' },
  '103': { meaning: 'subject to call @ ext.', category: 'status' },
  '105': { meaning: 'going for gas', category: 'status' },
  '106': { meaning: 'car wash', category: 'status' },
  '210': { meaning: 'strong armed robbery', category: 'violent' },
  '211': { meaning: 'armed robbery', category: 'violent' },
  '211A': { meaning: 'armed robbery alarm', category: 'violent' },
  '211B': { meaning: 'armed robbery alarm beacon', category: 'violent' },
  '211E': { meaning: 'extortion', category: 'violent' },
  '211C': { meaning: 'organized crime/conspiracy', category: 'violent' },
  '211T': { meaning: 'pronet alarm', category: 'violent' },
  '211H': { meaning: 'robbery home invasion', category: 'violent' },
  '236': { meaning: 'threat', category: 'violent' },
  '236E': { meaning: 'threat involving an educational facility', category: 'violent' },
  '237D': { meaning: 'dangerous drugs', category: 'drugs and vice' },
  '237G': { meaning: 'glue sniffing', category: 'drugs and vice' },
  '237L': { meaning: 'large quantity of marijuana', category: 'drugs and vice' },
  '237M': { meaning: 'marijuana report', category: 'drugs and vice' },
  '237N': { meaning: 'narcotics', category: 'drugs and vice' },
  '237P': { meaning: 'prescription violation', category: 'drugs and vice' },
  '239': { meaning: 'fight', category: 'violent' },
  '240': { meaning: 'assault', category: 'violent' },
  '240C': { meaning: 'escape', category: 'violent' },
  '240E': { meaning: 'reckless endangerment', category: 'violent' },
  '240R': { meaning: 'resisting arrest', category: 'violent' },
  '245': { meaning: 'aggravated assault', category: 'violent' },
  '245A': { meaning: 'abuse/neg of vulnerable adult', category: 'violent' },
  '245F': { meaning: 'abuse / neg of vulnerable adult dv', category: 'violent' },
  '246': { meaning: 'unconfirmed report of sniper', category: 'violent' },
  '246C': { meaning: 'confirmed report of sniper', category: 'officer emergency' },
  '250': { meaning: 'harassment', category: 'disturbance' },
  '250C': { meaning: 'cyberbullying', category: 'disturbance' },
  '251': { meaning: 'stalking', category: 'disturbance' },
  '260': { meaning: 'sexual abuse of adult', category: 'violent' },
  '260J': { meaning: 'sexual abuse of juvenile', category: 'violent' },
  '260L': { meaning: 'lure minor for sex', category: 'violent' },
  '261': { meaning: 'sexual assault', category: 'violent' },
  '261B': { meaning: 'bigamy, adultery, etc', category: 'violent' },
  '262': { meaning: 'sex offender registration violation', category: 'warrants and custody' },
  '300': { meaning: 'gambling', category: 'drugs and vice' },
  '301': { meaning: 'prostitution', category: 'drugs and vice' },
  '301A': { meaning: 'solicitation for prostitution', category: 'drugs and vice' },
  '301E': { meaning: 'escort violation', category: 'drugs and vice' },
  '301I': { meaning: 'prostitution - illegal enterprise', category: 'drugs and vice' },
  '301J': { meaning: 'prostitution - child', category: 'drugs and vice' },
  '301L': { meaning: 'escort license violation', category: 'drugs and vice' },
  '301M': { meaning: 'massage violation', category: 'drugs and vice' },
  '301P': { meaning: 'pandering/pimping - adult', category: 'drugs and vice' },
  '302': { meaning: 'internet/computer crimes', category: 'drugs and vice' },
  '302C': { meaning: 'cyber stalking/computer tampering', category: 'drugs and vice' },
  '302E': { meaning: 'computer chldporn/exploit', category: 'drugs and vice' },
  '302F': { meaning: 'internet/computer fraud', category: 'drugs and vice' },
  '302H': { meaning: 'internet/computer hack/intru', category: 'drugs and vice' },
  '302T': { meaning: 'sexting', category: 'drugs and vice' },
  '310': { meaning: 'molesting', category: 'violent' },
  '311': { meaning: 'indecent exposure', category: 'drugs and vice' },
  '311A': { meaning: 'urinating in public', category: 'drugs and vice' },
  '312': { meaning: 'child neglect', category: 'welfare' },
  '312A': { meaning: 'child abuse', category: 'welfare' },
  '312C': { meaning: 'contribute to delinquency of minor', category: 'welfare' },
  '315': { meaning: 'forgery', category: 'property' },
  '315B': { meaning: 'forgery at bank/credit union', category: 'property' },
  '315C': { meaning: 'money laundering', category: 'property' },
  '315D': { meaning: 'theft of credit card', category: 'property' },
  '315I': { meaning: 'identity theft', category: 'property' },
  '315M': { meaning: 'counterfeit currency', category: 'property' },
  '315P': { meaning: 'piracy of dvd/cd', category: 'property' },
  '315R': { meaning: 'registered trademark violation', category: 'property' },
  '315T': { meaning: 'taking id of another-attc', category: 'property' },
  '316': { meaning: 'non-sufficient funds / closed account', category: 'property' },
  '317': { meaning: 'soliciting', category: 'other' },
  '318': { meaning: 'theft by fraud', category: 'property' },
  '318E': { meaning: 'financial exploitation of elderly', category: 'property' },
  '319': { meaning: 'loss report', category: 'property' },
  '390': { meaning: 'drunk disturbing/down/car', category: 'drugs and vice' },
  '390A': { meaning: 'transport to detox facility', category: 'drugs and vice' },
  '390D': { meaning: 'drunk driver', category: 'traffic' },
  '390L': { meaning: 'liquor violation', category: 'drugs and vice' },
  '390U': { meaning: 'underage liquor violation', category: 'drugs and vice' },
  '415A': { meaning: 'harassing phone calls', category: 'disturbance' },
  '415B': { meaning: 'criminal damage', category: 'property' },
  '415C': { meaning: 'curfew violation', category: 'disturbance' },
  '415E': { meaning: 'loud noise disturbance', category: 'disturbance' },
  '415F': { meaning: 'domestic violence', category: 'violent' },
  '415G': { meaning: 'shots fired', category: 'violent' },
  '415H': { meaning: 'animals disturbing', category: 'disturbance' },
  '415I': { meaning: 'incorrigible juvenile', category: 'disturbance' },
  '415J': { meaning: 'juveniles disturbing', category: 'disturbance' },
  '415L': { meaning: 'loitering', category: 'disturbance' },
  '415O': { meaning: 'obstructing thoroughfare', category: 'disturbance' },
  '415P': { meaning: 'loud party disturbance', category: 'disturbance' },
  '415W': { meaning: 'weapon misuse/violation', category: 'violent' },
  '417': { meaning: 'subject threatening', category: 'violent' },
  '417B': { meaning: 'barricade', category: 'violent' },
  '417G': { meaning: 'subject with a gun', category: 'violent' },
  '417K': { meaning: 'subject with a knife', category: 'violent' },
  '418': { meaning: 'civil matter - stand by', category: 'disturbance' },
  '418A': { meaning: 'landlord/tenant dispute', category: 'disturbance' },
  '418B': { meaning: 'neighbor dispute', category: 'disturbance' },
  '418D': { meaning: 'illegal dumping', category: 'disturbance' },
  '418G': { meaning: 'unwanted guest', category: 'disturbance' },
  '418H': { meaning: 'harbor/tran illegal', category: 'disturbance' },
  '418I': { meaning: 'immigration matter', category: 'disturbance' },
  '418O': { meaning: 'civil matter - order of protection to be served', category: 'disturbance' },
  '418T': { meaning: 'trespassing', category: 'disturbance' },
  '418U': { meaning: 'solicitation door to door', category: 'disturbance' },
  '418V': { meaning: 'street vending violation', category: 'disturbance' },
  '418W': { meaning: 'unlawful hire', category: 'disturbance' },
  '451': { meaning: 'homicide', category: 'violent' },
  '451C': { meaning: 'conspiracy to murder', category: 'violent' },
  '451O': { meaning: 'homicide - other agency assist', category: 'violent' },
  '459': { meaning: 'burglary', category: 'property' },
  '459A': { meaning: 'burglary alarm', category: 'property' },
  '459B': { meaning: 'burg com metal thft rel', category: 'property' },
  '459C': { meaning: 'burglary commercial', category: 'property' },
  '459F': { meaning: 'burglary from vehicle', category: 'property' },
  '459H': { meaning: 'burg res metal thft rel', category: 'property' },
  '459M': { meaning: 'burglary frm vehicle - catalytic converter', category: 'property' },
  '459R': { meaning: 'burglary residential', category: 'property' },
  '459T': { meaning: 'burglary alarm- video/sound monitored', category: 'property' },
  '459V': { meaning: 'burglary of vending machine', category: 'property' },
  '487': { meaning: 'theft', category: 'property' },
  '487A': { meaning: 'purse snatch', category: 'property' },
  '487B': { meaning: 'shoplifting', category: 'property' },
  '487C': { meaning: 'theft catalytic converter', category: 'property' },
  '487F': { meaning: 'theft from vehicle', category: 'property' },
  '487I': { meaning: 'stolen bicycle', category: 'property' },
  '487J': { meaning: 'stolen property', category: 'property' },
  '487L': { meaning: 'locate only vehicle', category: 'property' },
  '487LP': { meaning: 'stolen license plate', category: 'property' },
  '487M': { meaning: 'bait vehicle', category: 'property' },
  '487P': { meaning: 'stolen police car', category: 'property' },
  '487V': { meaning: 'stolen vehicle', category: 'property' },
  '487W': { meaning: 'auto theft - watch your car program vehicle', category: 'property' },
  '487Y': { meaning: 'theft of metal', category: 'property' },
  '488I': { meaning: 'recovered bicycle', category: 'property' },
  '488P': { meaning: 'recovery f.o.j./property', category: 'property' },
  '488V': { meaning: 'recovery of vehicle', category: 'property' },
  '488W': { meaning: 'recovery of watch your car program vehicle', category: 'property' },
  '491': { meaning: 'kidnapping, adult/juvenile (not sexually motivated)', category: 'violent' },
  '491A': { meaning: 'custodial interference', category: 'violent' },
  '491B': { meaning: 'kidnapping (sexually motivated)', category: 'violent' },
  '491C': { meaning: 'access interference', category: 'violent' },
  '491D': { meaning: 'kidnapping - adult-no sp id\'d juv (sex. motivated)', category: 'violent' },
  '491U': { meaning: 'kidnapping, juvenile-sp id\'d (sexually motivated)', category: 'violent' },
  '492': { meaning: 'human smuggling', category: 'violent' },
  '500': { meaning: 'generic', category: 'other' },
  '500C': { meaning: 'crowd management', category: 'other' },
  '500D': { meaning: 'drone enforcement', category: 'other' },
  '501': { meaning: 'false reporting', category: 'warrants and custody' },
  '502': { meaning: 'judicial interference / obstructing justice', category: 'warrants and custody' },
  '503': { meaning: 'city ordinance offense', category: 'other' },
  '503F': { meaning: 'fireworks', category: 'fire and hazard' },
  '503G': { meaning: 'graffiti', category: 'property' },
  '504F': { meaning: 'federal interaction', category: 'warrants and custody' },
  '508': { meaning: 'traffic control', category: 'traffic' },
  '510': { meaning: 'speeding or racing', category: 'traffic' },
  '510F': { meaning: 'felony flight', category: 'traffic' },
  '511F': { meaning: 'foj felony warrant', category: 'warrants and custody' },
  '511M': { meaning: 'foj misdemeanor warrant', category: 'warrants and custody' },
  '511P': { meaning: 'subject stop', category: 'warrants and custody' },
  '511T': { meaning: 'tow request', category: 'traffic' },
  '511V': { meaning: 'vehicle stop', category: 'traffic' },
  '511W': { meaning: 'foj warrant pickup', category: 'warrants and custody' },
  '585': { meaning: 'traffic hazard', category: 'traffic' },
  '586': { meaning: 'illegal parking', category: 'traffic' },
  '601': { meaning: 'missing person', category: 'welfare' },
  '601F': { meaning: 'found missing person', category: 'welfare' },
  '601J': { meaning: 'missing juvenile', category: 'welfare' },
  '601O': { meaning: 'missing person other agency', category: 'welfare' },
  '601T': { meaning: 'truancy', category: 'welfare' },
  '647': { meaning: 'suspicious person', category: 'suspicious' },
  '647V': { meaning: 'suspicious person in vehicle', category: 'suspicious' },
  '647W': { meaning: 'suspicious person - watch your car program', category: 'suspicious' },
  '651': { meaning: 'loose animals', category: 'disturbance' },
  '651A': { meaning: 'injured animals', category: 'disturbance' },
  '707': { meaning: 'bomb threat', category: 'violent' },
  '707B': { meaning: 'nuclear/biological/chem situation', category: 'violent' },
  '707R': { meaning: 'radioactive material', category: 'violent' },
  '710G': { meaning: 'public gathering violation', category: 'disturbance' },
  '711': { meaning: 'intensive patrol', category: 'other' },
  '711C': { meaning: 'community engagement', category: 'other' },
  '900': { meaning: 'check welfare', category: 'welfare' },
  '900B': { meaning: 'open door, window, gate', category: 'welfare' },
  '900H': { meaning: 'subject in the street', category: 'welfare' },
  '900I': { meaning: 'medical identification', category: 'medical' },
  '900M': { meaning: 'mobile alarm', category: 'welfare' },
  '900V': { meaning: 'subject passed out in vehicle', category: 'medical' },
  '901': { meaning: 'injured or sick person', category: 'medical' },
  '901C': { meaning: 'cutting/stabbing', category: 'violent' },
  '901G': { meaning: 'shooting', category: 'violent' },
  '901H': { meaning: 'dead body', category: 'medical' },
  '901M': { meaning: 'medical practice violation', category: 'medical' },
  '901O': { meaning: 'overdose victim', category: 'medical' },
  '901U': { meaning: 'suicide', category: 'mental health' },
  '901X': { meaning: 'attempt suicide', category: 'mental health' },
  '906': { meaning: 'officer needs help', category: 'officer emergency' },
  '907': { meaning: 'back-up', category: 'status' },
  '911C': { meaning: '911 hang up cleared call', category: 'welfare' },
  '911H': { meaning: '911 hang-up call', category: 'welfare' },
  '914': { meaning: 'fire follow-up', category: 'fire and hazard' },
  '915': { meaning: 'arson', category: 'fire and hazard' },
  '915B': { meaning: 'fire bomb', category: 'fire and hazard' },
  '915H': { meaning: 'hazardous materials', category: 'fire and hazard' },
  '915I': { meaning: 'illegal burning', category: 'fire and hazard' },
  '915U': { meaning: 'undetermined fire', category: 'fire and hazard' },
  '917': { meaning: 'abandoned vehicle', category: 'traffic' },
  '918': { meaning: 'mentally ill subject', category: 'mental health' },
  '918H': { meaning: 'hospital to hospital transport', category: 'medical' },
  '918T': { meaning: 'mentally ill subj. transport', category: 'mental health' },
  '921': { meaning: 'prowler', category: 'suspicious' },
  '921P': { meaning: 'peeping tom', category: 'suspicious' },
  '926': { meaning: 'wrecker from list', category: 'traffic' },
  '926N': { meaning: 'vehicle seizure', category: 'traffic' },
  '927': { meaning: 'unknown trouble', category: 'suspicious' },
  '928': { meaning: 'found property', category: 'property' },
  '928E': { meaning: 'found explosives', category: 'property' },
  '928I': { meaning: 'found bicycle', category: 'property' },
  '928N': { meaning: 'found narcotics', category: 'property' },
  '960': { meaning: 'police aircraft down - no injuries/property damage', category: 'officer emergency' },
  '960A': { meaning: 'police aircraft down - w/ injuries/damage', category: 'officer emergency' },
  '961': { meaning: 'accident - no injuries', category: 'traffic' },
  '961H': { meaning: 'hit & run accident no injury', category: 'traffic' },
  '962': { meaning: 'accident with injuries', category: 'traffic' },
  '962H': { meaning: 'hit & run accident with injuries', category: 'traffic' },
  '963': { meaning: 'accident - fatality', category: 'traffic' },
  '963H': { meaning: 'hit & run fatality', category: 'traffic' },
  '964T': { meaning: 'translation detail', category: 'other' },
  '965': { meaning: 'ba operator needed', category: 'other' },
  '966': { meaning: 'crime lab print specialist', category: 'other' },
  '998': { meaning: 'officer involved shooting', category: 'officer emergency' },
  '999': { meaning: 'officer needs help urgently', category: 'officer emergency' },
  '10-1': { meaning: 'signal weak', category: 'status' },
  '10-2': { meaning: 'signal good', category: 'status' },
  '10-4': { meaning: 'affirmative (ok)', category: 'status' },
  '10-5': { meaning: 'relay (to)', category: 'status' },
  '10-6': { meaning: 'busy', category: 'status' },
  '10-7': { meaning: 'going off duty/out of service', category: 'status' },
  '10-8': { meaning: 'in service', category: 'status' },
  '10-9': { meaning: 'say again', category: 'status' },
  '10-11': { meaning: 'on duty', category: 'status' },
  '10-12': { meaning: 'stand-by (stop)', category: 'status' },
  '10-17': { meaning: 'enroute', category: 'status' },
  '10-20': { meaning: 'location', category: 'status' },
  '10-21': { meaning: 'call by phone', category: 'status' },
  '10-22': { meaning: 'no further action', category: 'status' },
  '10-23': { meaning: 'arrived at scene', category: 'status' },
  '10-25': { meaning: 'meet', category: 'status' },
  '10-27': { meaning: 'driver license/permit information', category: 'status' },
  '10-28': { meaning: 'ownership information/check full registration', category: 'status' },
  '10-29': { meaning: 'records check/warrant information', category: 'status' },
  '10-31': { meaning: 'pick up papers', category: 'status' },
  '10-33': { meaning: 'help me quick', category: 'officer emergency' },
  '10-34': { meaning: 'correct time', category: 'status' },
  '10-40': { meaning: 'out of service-subject to call', category: 'status' },
  '10-42': { meaning: 'prisoner in custody or booking', category: 'warrants and custody' },
  '10-43': { meaning: 'no traffic your unit', category: 'status' },
  '10-44': { meaning: 'does not conform with rules and regulations', category: 'status' },
  '10-46': { meaning: 'checking for traffic', category: 'status' },
  '10-48': { meaning: 'officer at home', category: 'status' },
  '10-49': { meaning: 'confidential information', category: 'status' },
  '10-50': { meaning: 'switch/ing to channel', category: 'status' },
  '10-51': { meaning: 'felony warrant outstanding', category: 'warrants and custody' },
  '10-52': { meaning: 'misdemeanor warrant outstanding', category: 'warrants and custody' },
  '10-57': { meaning: 'you have possible dangerous subject, back-up enroute', category: 'officer emergency' },
  '10-60': { meaning: 'female officer for search', category: 'status' },
  '10-68': { meaning: 'court attendance', category: 'status' },
  '10-70': { meaning: 'pr contact', category: 'status' },
  '10-71': { meaning: 'police range', category: 'status' },
  '10-73': { meaning: 'equipment transfer', category: 'status' },
  '10-74': { meaning: 'minor repair to vehicle', category: 'status' },
  '10-76': { meaning: 'notify owner of vehicle recovery', category: 'status' },
  '10-77': { meaning: 'notify parent of juvenile detention', category: 'status' },
  '10-79': { meaning: 'emergency message', category: 'status' },
  '10-85': { meaning: 'wires down (power, phone)', category: 'fire and hazard' },
  '10-86': { meaning: 'irrigation water on street', category: 'public works' },
  '10-87': { meaning: 'broken water main', category: 'public works' },
  '10-88': { meaning: 'damaged sidewalk', category: 'public works' },
  '10-89': { meaning: 'holes in street', category: 'public works' },
  '10-90': { meaning: 'traffic signals out of order', category: 'traffic' },
  '10-91': { meaning: 'assist motorist', category: 'traffic' },
  '10-92': { meaning: 'wagon wanted', category: 'status' },
}
